controller_manager:
  ros__parameters:
    update_rate: 30
    use_sym_time: true:

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['fl_wheel_joint', 'rl_wheel_joint']
    right_wheel_names: ['fr_wheel_joint', 'rr_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: true

    # open_loop: false

    wheels_per_side: 2
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.x.has_velocity_limits: false
    # angular.x.has_acceleration_limits: false
    # angular.x.has_jerk_limits: false
    # angular.x.max_velocity: NAN
    # angular.x.min_velocity: NAN
    # angular.x.max_jerk: NAN
    # angular.x.min_jerk: NAN

# joint_broad:
#   ros__parameters: